POS/Pages/POS_page/A.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    public class AModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;

        public AModel(POS.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Activity> Activity { get;set; }

        public async Task OnGetAsync()
        {
            Activity = await _context.Activities
                .Include(a => a.Task).ToListAsync();
        }
    }
}

POS/Pages/POS_page/All.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    [Microsoft.AspNetCore.Authorization.Authorize]

    public class AllModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public AllModel(POS.Data.ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<PosTask> PosTask { get;set; }

        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            PosTask = await _context.Tasks
                .Include(p => p.User).Where(x => x.UserId == user.Id).OrderByDescending(x => x.Date).ToListAsync();
        }
    }
}

POS/Pages/POS_page/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using POS.Data;

namespace POS.Pages.POS_page
{
    [Microsoft.AspNetCore.Authorization.Authorize]

    public class CreateModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CreateModel(POS.Data.ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult OnGet()
        {
        ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return Page();
        }

        [BindProperty]
        public PosTask PosTask { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);
            PosTask.Title = PosTask.Date.ToString("ddd dd MMM, yyyy");
            PosTask.UserId = user.Id;
            PosTask.MoniePointCharges = 0;
            //PosTask.A_Pay = 0;
            PosTask.CityCharges = 0;
            //PosTask.P_Pay = 0;
            PosTask.TotalCharges = 0;
            _context.Tasks.Add(PosTask);
            await _context.SaveChangesAsync();

            Expenditure e = new Expenditure();
            e.Date = DateTime.UtcNow.AddHours(1);
            e.TaskId = PosTask.Id;
            e.Description = "no expenses recorded";
            e.Amount = 0;
            _context.Expenditures.Add(e);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Details", new { id = PosTask.Id });
        }
    }
}

POS/Pages/POS_page/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    public class DeleteModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;

        public DeleteModel(POS.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public PosTask PosTask { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PosTask = await _context.Tasks
                .Include(p => p.User).FirstOrDefaultAsync(m => m.Id == id);

            if (PosTask == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PosTask = await _context.Tasks.FindAsync(id);

            if (PosTask != null)
            {
                _context.Tasks.Remove(PosTask);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

POS/Pages/POS_page/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    public class DetailsModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;

        public DetailsModel(POS.Data.ApplicationDbContext context)
        {
            _context = context;
        }
        [BindProperty]
        public decimal MachineAfter { get; set; }

        [BindProperty]
        public decimal CashAfter { get; set; }

        [BindProperty]
        public long TID { get; set; }
        [BindProperty]
        public PosTask PosTask { get; set; }
        public IList<Activity> ActivityList { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (id == null)
            {
                return NotFound();    
            }

            PosTask = await _context.Tasks
                .Include(p => p.User).FirstOrDefaultAsync(m => m.Id == id);

            if (PosTask == null)
            {
                return NotFound();
            }

            Expenditure = await _context.Expenditures
               .Include(e => e.Task).FirstOrDefaultAsync(m => m.TaskId == id);
            ActivityList = await _context.Activities
                .Include(a => a.Task).OrderByDescending(c => c.Date).Where(m => m.TaskId == id).ToListAsync();

            //
            var t = await _context.Tasks.FirstOrDefaultAsync(x => x.Id == id);
            var transaction = await _context.Activities.Where(x => x.TaskId == id).ToListAsync();
            var xExpenditure = await _context.Expenditures
                .Include(e => e.Task).FirstOrDefaultAsync(m => m.TaskId == id);

            var xTotalCharges = transaction.Sum(x => x.CityCharge);
            var xMoniePointCharges = transaction.Sum(x => x.moniepointCharge);
            t.TotalCharges = xTotalCharges;
            t.MoniePointCharges = xMoniePointCharges;
            var xCityCharges = xTotalCharges - xMoniePointCharges;
            t.CityCharges = xCityCharges;

            ///
            //p
            double fp = 40 / 100d;
            double xp = 20 / 100d;
            decimal ppercent = Convert.ToDecimal(fp) * Convert.ToDecimal(xCityCharges);
            decimal opercent = Convert.ToDecimal(fp) * Convert.ToDecimal(xCityCharges);
            decimal citypercent = Convert.ToDecimal(xp) * Convert.ToDecimal(xCityCharges);

            t.Admin_Pay = ppercent;
            t.Rep_Pay = opercent;
            t.Machine_Pay = citypercent;
            _context.Attach(t).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return Page();
        }

        [BindProperty]
        public Activity Activity { get; set; }
        public Expenditure Expenditure { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Activities.Add(Activity);
            await _context.SaveChangesAsync();
            //
          





            return RedirectToPage("./Details", new { id = Activity.TaskId });
        }

        public async Task<IActionResult> OnPostUpdateTask()
        {
           var PosTask = await _context.Tasks
                .Include(p => p.User).FirstOrDefaultAsync(m => m.Id == TID);

            PosTask.AmountInCashAfter = CashAfter;
            PosTask.AmountInMachineAfter = MachineAfter;
            _context.Attach(PosTask).State = EntityState.Modified;
            await _context.SaveChangesAsync();

            return RedirectToPage("./Details", new { id = PosTask.Id });
        }
    }
}

POS/Pages/POS_page/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    public class EditModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;

        public EditModel(POS.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public PosTask PosTask { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PosTask = await _context.Tasks
                .Include(p => p.User).FirstOrDefaultAsync(m => m.Id == id);

            if (PosTask == null)
            {
                return NotFound();
            }
           ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(PosTask).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PosTaskExists(PosTask.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool PosTaskExists(long id)
        {
            return _context.Tasks.Any(e => e.Id == id);
        }
    }
}

POS/Pages/POS_page/EditA.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    public class EditAModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;

        public EditAModel(POS.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Activity Activity { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Activity = await _context.Activities
                .Include(a => a.Task).FirstOrDefaultAsync(m => m.Id == id);

            if (Activity == null)
            {
                return NotFound();
            }
           ViewData["TaskId"] = new SelectList(_context.Tasks, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Activity).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ActivityExists(Activity.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ActivityExists(long id)
        {
            return _context.Activities.Any(e => e.Id == id);
        }
    }
}

POS/Pages/POS_page/EditExp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    [Microsoft.AspNetCore.Authorization.Authorize]

    public class EditExpModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;

        public EditExpModel(POS.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Expenditure Expenditure { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Expenditure = await _context.Expenditures
                .Include(e => e.Task).FirstOrDefaultAsync(m => m.Id == id);

            if (Expenditure == null)
            {
                return NotFound();
            }
           ViewData["TaskId"] = new SelectList(_context.Tasks, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Expenditure).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ExpenditureExists(Expenditure.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Details", new { id = Expenditure.TaskId });
        }

        private bool ExpenditureExists(long id)
        {
            return _context.Expenditures.Any(e => e.Id == id);
        }
    }
}

POS/Pages/POS_page/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using POS.Data;

namespace POS.Pages.POS_page
{
    [Microsoft.AspNetCore.Authorization.Authorize]

    public class IndexModel : PageModel
    {
        private readonly POS.Data.ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public IndexModel(POS.Data.ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<PosTask> PosTask { get;set; }

        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            PosTask = await _context.Tasks.Include(p => p.Activities)
                .Include(p => p.User).Where(x => x.Close == false).Where(x => x.UserId == user.Id).OrderByDescending(x=>x.Date).ToListAsync();
        }
    }
}

POS/Pages/POS_page/A.cshtml
@page
@model POS.Pages.POS_page.AModel

@{
    ViewData["Title"] = "A";
}

<h1>A</h1>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Activity[0].Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Activity[0].TransactionType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Activity[0].Amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Activity[0].moniepointCharge)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Activity[0].CityCharge)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Activity[0].Task)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Activity)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TransactionType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.moniepointCharge)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CityCharge)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Task.Id)
                    </td>
                    <td>
                        <a asp-page="./EditA" asp-route-id="@item.Id">Edit</a> |

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

POS/Pages/POS_page/All.cshtml
@page
@model POS.Pages.POS_page.AllModel

@{
    ViewData["Title"] = "All";
}

<h1>All</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].AmountInMachineBefore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].AmountInCashBefore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].AmountInMachineAfter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].AmountInCashAfter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].TotalCharges)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].MoniePointCharges)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].CityCharges)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].Admin_Pay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].Rep_Pay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].Machine_Pay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].Close)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosTask[0].User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.PosTask) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountInMachineBefore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountInCashBefore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountInMachineAfter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountInCashAfter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalCharges)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MoniePointCharges)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CityCharges)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Admin_Pay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rep_Pay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Machine_Pay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Close)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Id)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

POS/Pages/POS_page/Create.cshtml
@page
@model POS.Pages.POS_page.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pos Task</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="PosTask.Date" class="control-label"></label>
                <input asp-for="PosTask.Date" class="form-control" value="@DateTime.UtcNow"/>
                <span asp-validation-for="PosTask.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PosTask.AmountInMachineBefore" class="control-label"></label>
                <input asp-for="PosTask.AmountInMachineBefore" class="form-control" />
                <span asp-validation-for="PosTask.AmountInMachineBefore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PosTask.AmountInCashBefore" class="control-label"></label>
                <input asp-for="PosTask.AmountInCashBefore" class="form-control" />
                <span asp-validation-for="PosTask.AmountInCashBefore" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

POS/Pages/POS_page/Details.cshtml
@page
@model POS.Pages.POS_page.DetailsModel

@{
    ViewData["Title"] = "Details";
}


<h5>Add New Transaction</h5>

<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Activity.Date" class="control-label"></label>
        <input asp-for="Activity.Date" class="form-control" value="@DateTime.UtcNow" />
        <span asp-validation-for="Activity.Date" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Activity.TransactionType" class="control-label"></label>
        <select asp-for="Activity.TransactionType" class="form-control">
            <option value="DEPOSIT">DEPOSIT</option>
            <option value="TRANSFER">TRANSFER</option>
            <option value="WITHDRAW">WITHDRAW</option>
            <option value="BILLPAYMENT">BILLPAYMENT</option>
        </select>
        <span asp-validation-for="Activity.TransactionType" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Activity.Amount" class="control-label"></label>
        <input asp-for="Activity.Amount" class="form-control" />
        <span asp-validation-for="Activity.Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Activity.moniepointCharge" class="control-label"></label>
        <input asp-for="Activity.moniepointCharge" class="form-control" />
        <span asp-validation-for="Activity.moniepointCharge" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Activity.CityCharge" class="control-label"></label>
        <input asp-for="Activity.CityCharge" class="form-control" />
        <span asp-validation-for="Activity.CityCharge" class="text-danger"></span>
    </div>
    <input asp-for="Activity.TaskId" value="@Model.PosTask.Id" hidden="hidden" />


    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
</form>
<hr />
<div class="table-responsive">
    <table id="example" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>S/N</th>
                <th>
                    Date
                </th>
                <th>
                    Transaction Type
                </th>
                <th>
                    Amount
                </th>
                <th>
                    moniepoint Charge
                </th>
                <th>
                    City Charge
                </th>

            </tr>
        </thead>
        @{
            int sn = 0;
        }
        <tbody>
            @foreach (var item in Model.ActivityList)
            {
                <tr>
                    <td>
                        @{sn++;
                        }
                        @sn

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TransactionType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.moniepointCharge)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CityCharge)
                    </td>

                </tr>
            }
        </tbody>
    </table>
    </div>
    <hr />
    <div>
        <h4>Expenditure</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Expenditure.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Expenditure.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Expenditure.Date)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Expenditure.Date)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Expenditure.Amount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Expenditure.Amount)
            </dd>
            
        </dl>
    </div>
    <div>
        <a asp-page="./EditExp" asp-route-id="@Model.Expenditure.Id">Edit</a> |
        <a asp-page="./Index">Back to List</a>
    </div>
   
<hr />
<form method="post" asp-page-handler="UpdateTask">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="TID" value="@Model.PosTask.Id" />
    <div class="form-group">
        <label asp-for="CashAfter" class="control-label">Cash at Hand After Work</label>
        <input asp-for="CashAfter" class="form-control" value="@Model.PosTask.AmountInCashAfter"/>
        <span asp-validation-for="CashAfter" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MachineAfter" class="control-label"></label>
        <input asp-for="MachineAfter" class="form-control" value="@Model.PosTask.AmountInMachineAfter"/>
        <span asp-validation-for="MachineAfter" class="text-danger"></span>
    </div>
  

    <div class="form-group">
        <input type="submit" value="Update" class="btn btn-primary" />
    </div>
</form>